#!/usr/bin/env python
"""Container-only single/multi-node reward deployment."""

from __future__ import annotations

import argparse
import socket
import subprocess
import sys
import time
import urllib.request


API_PORT = 20111


def parse_args() -> argparse.Namespace:
    # Match torchrun-style deployment arguments while keeping service ports fixed.
    parser = argparse.ArgumentParser(description="Deploy a KernelGym reward node inside an existing container")
    parser.add_argument("--nnodes", type=int, default=1)
    parser.add_argument("--node-rank", type=int, default=None)
    parser.add_argument("--master-addr", default="")
    parser.add_argument("--master-port", type=int, default=API_PORT)
    return parser.parse_args()


def local_ids() -> set[str]:
    # Gather hostnames and IPs visible from inside the container for master detection.
    ids = {"localhost", "127.0.0.1"}
    hostname = socket.gethostname()
    if hostname:
        ids.add(hostname)
    fqdn = socket.getfqdn()
    if fqdn:
        ids.add(fqdn)
    try:
        ids.update(socket.gethostbyname_ex(hostname)[2])
    except OSError:
        pass
    try:
        probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        probe.connect(("1.1.1.1", 80))
        ids.add(probe.getsockname()[0])
        probe.close()
    except OSError:
        pass
    try:
        proc = subprocess.run(["hostname", "-I"], check=False, text=True, stdout=subprocess.PIPE)
        ids.update(item for item in proc.stdout.split() if item)
    except OSError:
        pass
    return {item for item in ids if item}


def run(command: list[str], *, allow_failure: bool = False) -> None:
    # Keep subprocess handling explicit so deployment failures surface directly.
    proc = subprocess.run(command, check=False)
    if proc.returncode and not allow_failure:
        raise SystemExit(proc.returncode)


def wait_api(master_addr: str) -> None:
    # Worker nodes should not start until the primary API is reachable.
    url = f"http://{master_addr}:{API_PORT}/health"
    deadline = time.time() + 180
    last_error: Exception | None = None
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=5) as response:
                if response.status < 500:
                    print(f"API ready: {url}")
                    return
        except Exception as exc:
            last_error = exc
        time.sleep(3)
    raise SystemExit(f"API did not become ready at {url}: {last_error}")


def start_primary(node_rank: int | None) -> None:
    # Rank 0 runs API, Redis, monitor, and local workers through the service CLI.
    print(f"Starting primary node rank={node_rank if node_rank is not None else 'auto'}")
    run([sys.executable, "-m", "kernelgym.cli.service", "start-local", "--profile", "v1"])
    wait_api("127.0.0.1")


def start_worker(master_addr: str, node_rank: int) -> None:
    # Worker configuration is generated by kernelgym.cli.service from deployment_profiles.py.
    print(f"Starting worker node rank={node_rank} master={master_addr}:{API_PORT}")
    run([sys.executable, "-m", "kernelgym.cli.service", "stop", "--profile", "v1"], allow_failure=True)
    wait_api(master_addr)
    run(
        [
            sys.executable,
            "-m",
            "kernelgym.cli.service",
            "start-worker-node",
            "--profile",
            "v1",
            "--master-addr",
            master_addr,
            "--node-rank",
            str(node_rank),
        ]
    )


def validate(args: argparse.Namespace) -> None:
    # Validate topology before touching running services.
    if args.nnodes < 1:
        raise SystemExit("--nnodes must be a positive integer")
    if args.master_port != API_PORT:
        raise SystemExit(f"--master-port must be {API_PORT}; service ports are fixed in this repo")
    if args.nnodes == 1:
        return
    if not args.master_addr:
        raise SystemExit("--master-addr is required when --nnodes > 1")
    if args.node_rank is None:
        raise SystemExit("--node-rank is required when --nnodes > 1")
    if args.node_rank < 0 or args.node_rank >= args.nnodes:
        raise SystemExit("--node-rank must be an integer in [0, nnodes)")


def main() -> int:
    args = parse_args()
    validate(args)
    if args.nnodes == 1:
        start_primary(args.node_rank)
        return 0

    # Role is determined by whether this container can see itself as --master-addr.
    is_master = args.master_addr in local_ids()
    if is_master and args.node_rank != 0:
        raise SystemExit("The node matching --master-addr must use --node-rank 0")
    if not is_master and args.node_rank == 0:
        raise SystemExit("--node-rank 0 must run on the node matching --master-addr")
    if is_master:
        start_primary(args.node_rank)
    else:
        start_worker(args.master_addr, args.node_rank)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
